/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminDeveloperRequestsRouteImport } from './routes/admin.developer-requests'
import { Route as AdminDevelopersRouteImport } from './routes/admin.developers'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminProjectInvoicesRouteImport } from './routes/admin.project-invoices'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminWebPortalRouteImport } from './routes/admin.web-portal'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientImportantInfoRouteImport } from './routes/client.important-info'
import { Route as ClientInvoicesRouteImport } from './routes/client.invoices'
import { Route as ClientMessagesRouteImport } from './routes/client.messages'
import { Route as ClientProjectsRouteImport } from './routes/client.projects'
import { Route as ClientReviewsRouteImport } from './routes/client.reviews'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as DeveloperMessagesRouteImport } from './routes/developer.messages'
import { Route as DeveloperProjectsRouteImport } from './routes/developer.projects'
import { Route as AdminProjectIdRouteImport } from './routes/admin.project.$id'
import { Route as ClientProjectIdRouteImport } from './routes/client.project.$id'
import { Route as DeveloperProjectIdRouteImport } from './routes/developer.project.$id'
import { Route as ApiPublicHooksDispatchPushRouteImport } from './routes/api/public/hooks/dispatch-push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeveloperRequestsRoute = AdminDeveloperRequestsRouteImport.update({
  id: '/admin/developer-requests',
  path: '/admin/developer-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevelopersRoute = AdminDevelopersRouteImport.update({
  id: '/admin/developers',
  path: '/admin/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectInvoicesRoute = AdminProjectInvoicesRouteImport.update({
  id: '/admin/project-invoices',
  path: '/admin/project-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebPortalRoute = AdminWebPortalRouteImport.update({
  id: '/admin/web-portal',
  path: '/admin/web-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientImportantInfoRoute = ClientImportantInfoRouteImport.update({
  id: '/client/important-info',
  path: '/client/important-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/client/invoices',
  path: '/client/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/client/messages',
  path: '/client/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/client/projects',
  path: '/client/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientReviewsRoute = ClientReviewsRouteImport.update({
  id: '/client/reviews',
  path: '/client/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperMessagesRoute = DeveloperMessagesRouteImport.update({
  id: '/developer/messages',
  path: '/developer/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectsRoute = DeveloperProjectsRouteImport.update({
  id: '/developer/projects',
  path: '/developer/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectIdRoute = AdminProjectIdRouteImport.update({
  id: '/admin/project/$id',
  path: '/admin/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectIdRoute = ClientProjectIdRouteImport.update({
  id: '/client/project/$id',
  path: '/client/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperProjectIdRoute = DeveloperProjectIdRouteImport.update({
  id: '/developer/project/$id',
  path: '/developer/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDispatchPushRoute =
  ApiPublicHooksDispatchPushRouteImport.update({
    id: '/api/public/hooks/dispatch-push',
    path: '/api/public/hooks/dispatch-push',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/developer-requests': typeof AdminDeveloperRequestsRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/project-invoices': typeof AdminProjectInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/web-portal': typeof AdminWebPortalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/important-info': typeof ClientImportantInfoRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/project/$id': typeof AdminProjectIdRoute
  '/client/project/$id': typeof ClientProjectIdRoute
  '/developer/project/$id': typeof DeveloperProjectIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/developer-requests': typeof AdminDeveloperRequestsRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/project-invoices': typeof AdminProjectInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/web-portal': typeof AdminWebPortalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/important-info': typeof ClientImportantInfoRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/admin/project/$id': typeof AdminProjectIdRoute
  '/client/project/$id': typeof ClientProjectIdRoute
  '/developer/project/$id': typeof DeveloperProjectIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/developer-requests': typeof AdminDeveloperRequestsRoute
  '/admin/developers': typeof AdminDevelopersRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/project-invoices': typeof AdminProjectInvoicesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/web-portal': typeof AdminWebPortalRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/client/important-info': typeof ClientImportantInfoRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/projects': typeof ClientProjectsRoute
  '/client/reviews': typeof ClientReviewsRoute
  '/developer/messages': typeof DeveloperMessagesRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/admin/project/$id': typeof AdminProjectIdRoute
  '/client/project/$id': typeof ClientProjectIdRoute
  '/developer/project/$id': typeof DeveloperProjectIdRoute
  '/api/public/hooks/dispatch-push': typeof ApiPublicHooksDispatchPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/admin/clients'
    | '/admin/developer-requests'
    | '/admin/developers'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/project-invoices'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/web-portal'
    | '/blog/$slug'
    | '/client/important-info'
    | '/client/invoices'
    | '/client/messages'
    | '/client/projects'
    | '/client/reviews'
    | '/developer/messages'
    | '/developer/projects'
    | '/admin/'
    | '/client/'
    | '/developer/'
    | '/admin/project/$id'
    | '/client/project/$id'
    | '/developer/project/$id'
    | '/api/public/hooks/dispatch-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/admin/clients'
    | '/admin/developer-requests'
    | '/admin/developers'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/project-invoices'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/web-portal'
    | '/blog/$slug'
    | '/client/important-info'
    | '/client/invoices'
    | '/client/messages'
    | '/client/projects'
    | '/client/reviews'
    | '/developer/messages'
    | '/developer/projects'
    | '/admin'
    | '/client'
    | '/developer'
    | '/admin/project/$id'
    | '/client/project/$id'
    | '/developer/project/$id'
    | '/api/public/hooks/dispatch-push'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/admin/clients'
    | '/admin/developer-requests'
    | '/admin/developers'
    | '/admin/invoices'
    | '/admin/leads'
    | '/admin/project-invoices'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/web-portal'
    | '/blog_/$slug'
    | '/client/important-info'
    | '/client/invoices'
    | '/client/messages'
    | '/client/projects'
    | '/client/reviews'
    | '/developer/messages'
    | '/developer/projects'
    | '/admin/'
    | '/client/'
    | '/developer/'
    | '/admin/project/$id'
    | '/client/project/$id'
    | '/developer/project/$id'
    | '/api/public/hooks/dispatch-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDeveloperRequestsRoute: typeof AdminDeveloperRequestsRoute
  AdminDevelopersRoute: typeof AdminDevelopersRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminProjectInvoicesRoute: typeof AdminProjectInvoicesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminWebPortalRoute: typeof AdminWebPortalRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClientImportantInfoRoute: typeof ClientImportantInfoRoute
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientProjectsRoute: typeof ClientProjectsRoute
  ClientReviewsRoute: typeof ClientReviewsRoute
  DeveloperMessagesRoute: typeof DeveloperMessagesRoute
  DeveloperProjectsRoute: typeof DeveloperProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClientIndexRoute: typeof ClientIndexRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  AdminProjectIdRoute: typeof AdminProjectIdRoute
  ClientProjectIdRoute: typeof ClientProjectIdRoute
  DeveloperProjectIdRoute: typeof DeveloperProjectIdRoute
  ApiPublicHooksDispatchPushRoute: typeof ApiPublicHooksDispatchPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/developer-requests': {
      id: '/admin/developer-requests'
      path: '/admin/developer-requests'
      fullPath: '/admin/developer-requests'
      preLoaderRoute: typeof AdminDeveloperRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/developers': {
      id: '/admin/developers'
      path: '/admin/developers'
      fullPath: '/admin/developers'
      preLoaderRoute: typeof AdminDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/project-invoices': {
      id: '/admin/project-invoices'
      path: '/admin/project-invoices'
      fullPath: '/admin/project-invoices'
      preLoaderRoute: typeof AdminProjectInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/web-portal': {
      id: '/admin/web-portal'
      path: '/admin/web-portal'
      fullPath: '/admin/web-portal'
      preLoaderRoute: typeof AdminWebPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/important-info': {
      id: '/client/important-info'
      path: '/client/important-info'
      fullPath: '/client/important-info'
      preLoaderRoute: typeof ClientImportantInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/invoices': {
      id: '/client/invoices'
      path: '/client/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/client/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/reviews': {
      id: '/client/reviews'
      path: '/client/reviews'
      fullPath: '/client/reviews'
      preLoaderRoute: typeof ClientReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/messages': {
      id: '/developer/messages'
      path: '/developer/messages'
      fullPath: '/developer/messages'
      preLoaderRoute: typeof DeveloperMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/projects': {
      id: '/developer/projects'
      path: '/developer/projects'
      fullPath: '/developer/projects'
      preLoaderRoute: typeof DeveloperProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/project/$id': {
      id: '/admin/project/$id'
      path: '/admin/project/$id'
      fullPath: '/admin/project/$id'
      preLoaderRoute: typeof AdminProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/project/$id': {
      id: '/client/project/$id'
      path: '/client/project/$id'
      fullPath: '/client/project/$id'
      preLoaderRoute: typeof ClientProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/project/$id': {
      id: '/developer/project/$id'
      path: '/developer/project/$id'
      fullPath: '/developer/project/$id'
      preLoaderRoute: typeof DeveloperProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-push': {
      id: '/api/public/hooks/dispatch-push'
      path: '/api/public/hooks/dispatch-push'
      fullPath: '/api/public/hooks/dispatch-push'
      preLoaderRoute: typeof ApiPublicHooksDispatchPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDeveloperRequestsRoute: AdminDeveloperRequestsRoute,
  AdminDevelopersRoute: AdminDevelopersRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminProjectInvoicesRoute: AdminProjectInvoicesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminWebPortalRoute: AdminWebPortalRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClientImportantInfoRoute: ClientImportantInfoRoute,
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientProjectsRoute: ClientProjectsRoute,
  ClientReviewsRoute: ClientReviewsRoute,
  DeveloperMessagesRoute: DeveloperMessagesRoute,
  DeveloperProjectsRoute: DeveloperProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClientIndexRoute: ClientIndexRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  AdminProjectIdRoute: AdminProjectIdRoute,
  ClientProjectIdRoute: ClientProjectIdRoute,
  DeveloperProjectIdRoute: DeveloperProjectIdRoute,
  ApiPublicHooksDispatchPushRoute: ApiPublicHooksDispatchPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
